name: time_guard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_apps: ^2.2.0
  device_preview: ^1.1.0
  flutter_animate: ^4.2.0+1
  flutter_pin_code_fields: ^2.2.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.2.1
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  usage_stats: ^1.2.0
  # path_provider: ^2.1.1
  # image_picker: ^1.0.4


dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700