name: time_guard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  # app_usage: ^3.0.1
  cupertino_icons: ^1.0.2
  custom_pin_screen: ^0.3.0
  device_apps: ^2.2.0
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_pin_code_fields: ^2.2.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.2.1
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^5.0.2
  pin_plus_keyboard: ^2.0.6
  provider: ^6.0.5
  # pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.2
  usage_stats: ^1.2.0

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_icons:
  generate: true
  android: true
  ios: true
  image_path: assets/images/appicon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf

  # flutter pub run flutter_launcher_icons:main
